export const EN_DESCRIPTIONS: Record<string, string> = {
    "TIME": "Global time since engine start (seconds)",
    "PI": "Constant π (3.141592)",
    "TAU": "Constant τ (6.283185), equal to π × 2",
    "E": "Euler's number e (2.718281)",
    "OUTPUT_IS_SRGB": "True if output is sRGB (Compatibility renderer)",
    "CLIP_SPACE_FAR": "Far clip plane value (0.0 for Forward+/Mobile, 1.0 for Compatibility)",
    "VIEWPORT_SIZE": "Viewport size (pixels)",
    "CURRENT_RENDERER": "Current renderer type (0=Forward+, 1=Mobile, 2=Compatibility, 3=Forward)",
    "RENDERER_FORWARD_PLUS": "Forward+ renderer constant (value 0)",
    "RENDERER_MOBILE": "Mobile renderer constant (value 1)",
    "RENDERER_COMPATIBILITY": "Compatibility renderer constant (value 2)",
    "RENDERER_FORWARD": "Forward renderer constant (value 3), Godot 4.3+",
    "FRAGCOORD": "Fragment coordinates (x, y, z, w)",
    "FRONT_FACING": "Whether the primitive is front-facing",
    "VIEW_MATRIX": "World space → View space",
    "INV_VIEW_MATRIX": "View space → World space",
    "MAIN_CAM_INV_VIEW_MATRIX": "Main camera inverse view matrix / View space → World space (read-only)",
    "INV_PROJECTION_MATRIX": "Clip space → View space",
    "NODE_POSITION_WORLD": "Node position in world space",
    "NODE_POSITION_VIEW": "Node position in view space",
    "CAMERA_POSITION_WORLD": "Camera position in world space",
    "CAMERA_DIRECTION_WORLD": "Camera direction in world space",
    "CAMERA_VISIBLE_LAYERS": "Camera visible layer mask",
    "INSTANCE_ID": "Instance ID for instanced rendering (identifies each draw call)",
    "INSTANCE_CUSTOM": "Instance custom data",
    "VIEW_INDEX": "View index (multi-view rendering)",
    "VIEW_MONO_LEFT": "Monoscopic/left eye constant (0)",
    "VIEW_RIGHT": "Right eye constant (1)",
    "EYE_OFFSET": "Eye offset / World space (multi-view rendering)",
    "VERTEX_ID": "Vertex index in the vertex buffer",
    "CUSTOM0": "Custom vertex data channel 0",
    "CUSTOM1": "Custom vertex data channel 1",
    "CUSTOM2": "Custom vertex data channel 2",
    "CUSTOM3": "Custom vertex data channel 3",
    "VERTEX": "Vertex position (model space, read-write)",
    "NORMAL": "Normal vector (varies: model space in vertex, view space in fragment)",
    "TANGENT": "Tangent vector (varies: model space in vertex, view space in fragment)",
    "BINORMAL": "Binormal vector (varies: model space in vertex, view space in fragment)",
    "UV": "First UV coordinate set (read-write)",
    "UV2": "Second UV coordinate set (read-write)",
    "COLOR": "Vertex color (read-write)",
    "POINT_SIZE": "Point rendering size (read-write)",
    "MODELVIEW_MATRIX": "Model space → View space (read-write, recommended to avoid precision issues)",
    "MODELVIEW_NORMAL_MATRIX": "Model space → View space (normal transform matrix)",
    "MODEL_MATRIX": "Model space → World space (read-write)",
    "MODEL_NORMAL_MATRIX": "Model space → World space (normal transform matrix)",
    "PROJECTION_MATRIX": "View space → Clip space (read-write)",
    "BONE_INDICES": "Bone indices (for skinning)",
    "BONE_WEIGHTS": "Bone weights (for skinning)",
    "POSITION": "Varies by context: camera position (World space) in sky, final vertex position (Clip space, if written) in vertex_write",
    "ROUGHNESS": "Vertex lighting roughness",
    "Z_CLIP_SCALE": "Vertex scaling factor toward the camera",
    "VIEW": "Normalized vector from fragment to camera (view space)",
    "POINT_COORD": "Point coordinates / Screen space (for point rendering)",
    "LIGHT_VERTEX": "Adjustable copy of VERTEX / Default: view space (for light calculations)",
    "SCREEN_UV": "Screen-space UV coordinates",
    "DEPTH": "Custom depth value / NDC (if written)",
    "NORMAL_MAP": "Normal map vector (tangent space; write to override NORMAL)",
    "NORMAL_MAP_DEPTH": "Normal map depth scale factor (default 1.0)",
    "BENT_NORMAL_MAP": "Bent normal map / Tangent space (for ambient occlusion, write to modify ambient direction)",
    "ALBEDO": "Albedo color (read-write)",
    "ALPHA": "Alpha transparency (read-write, range 0..1)",
    "ALPHA_SCISSOR_THRESHOLD": "Alpha scissor threshold (fragments below this are discarded)",
    "ALPHA_HASH_SCALE": "Alpha hash scale",
    "ALPHA_ANTIALIASING_EDGE": "Alpha anti-aliasing edge",
    "ALPHA_TEXTURE_COORDINATE": "Alpha texture coordinate",
    "PREMUL_ALPHA_FACTOR": "Pre-multiplied alpha factor",
    "METALLIC": "Metallic (read-write, range 0..1)",
    "SPECULAR": "Specular (read-write, default 0.5)",
    "RIM": "Rim lighting intensity (range 0..1)",
    "RIM_TINT": "Rim lighting tint (0=white, 1=albedo color)",
    "CLEARCOAT": "Clearcoat intensity",
    "CLEARCOAT_GLOSS": "Clearcoat glossiness",
    "ANISOTROPY": "Anisotropic specular streak intensity",
    "ANISOTROPY_FLOW": "Anisotropic specular direction (for flow maps)",
    "SSS_STRENGTH": "Subsurface scattering strength",
    "SSS_TRANSMITTANCE_COLOR": "Subsurface scattering transmittance color",
    "SSS_TRANSMITTANCE_DEPTH": "Subsurface scattering transmittance depth",
    "SSS_TRANSMITTANCE_BOOST": "Subsurface scattering transmittance boost",
    "BACKLIGHT": "Backlight color, set in fragment shader, readable in light()",
    "AO": "Ambient occlusion intensity",
    "AO_LIGHT_AFFECT": "Ambient occlusion influence on real-time lighting (0..1)",
    "EMISSION": "Emission color (can exceed (1,1,1) for HDR)",
    "FOG": "Fog blend (use FOG.rgb and FOG.a)",
    "RADIANCE": "Environment map radiance blend",
    "IRRADIANCE": "Environment map irradiance blend",
    "TEXTURE": "Default texture (read-write)",
    "TEXTURE_PIXEL_SIZE": "Texture pixel size",
    "SCREEN_PIXEL_SIZE": "Screen pixel size",
    "SPHERE_INDEX": "Sphere index (XR multiview rendering)",
    "AT_HALF_RES_PASS": "Whether rendering the half-resolution sub-pass",
    "AT_QUARTER_RES_PASS": "Whether rendering the quarter-resolution sub-pass",
    "AT_CUBEMAP_PASS": "Whether rendering the radiance cubemap",
    "LIGHT0_ENABLED": "Whether light 0 is enabled",
    "LIGHT0_ENERGY": "Light 0 energy multiplier",
    "LIGHT0_DIRECTION": "Light 0 direction",
    "LIGHT0_COLOR": "Light 0 color",
    "LIGHT0_SIZE": "Light 0 angular diameter in the sky (radians)",
    "LIGHT1_ENABLED": "Whether light 1 is enabled",
    "LIGHT1_ENERGY": "Light 1 energy multiplier",
    "LIGHT1_DIRECTION": "Light 1 direction",
    "LIGHT1_COLOR": "Light 1 color",
    "LIGHT1_SIZE": "Light 1 angular diameter in the sky (radians)",
    "LIGHT2_ENABLED": "Whether light 2 is enabled",
    "LIGHT2_ENERGY": "Light 2 energy multiplier",
    "LIGHT2_DIRECTION": "Light 2 direction",
    "LIGHT2_COLOR": "Light 2 color",
    "LIGHT2_SIZE": "Light 2 angular diameter in the sky (radians)",
    "LIGHT3_ENABLED": "Whether light 3 is enabled",
    "LIGHT3_ENERGY": "Light 3 energy multiplier",
    "LIGHT3_DIRECTION": "Light 3 direction",
    "LIGHT3_COLOR": "Light 3 color",
    "LIGHT3_SIZE": "Light 3 angular diameter in the sky (radians)",
    "EYEDIR": "Normalized direction of the current pixel / World space (for procedural sky effects)",
    "SKY_COORDS": "Spherical UV coordinates (for panoramic textures)",
    "HALF_RES_COLOR": "Color value of the corresponding pixel in the half-resolution sub-pass",
    "QUARTER_RES_COLOR": "Color value of the corresponding pixel in the quarter-resolution sub-pass",
    "WORLD_POSITION": "Position of the current froxel in world space",
    "OBJECT_POSITION": "Position of the associated FogVolume center in world space",
    "UVW": "3D UV coordinates (for 3D texture mapping)",
    "SIZE": "FogVolume dimensions",
    "SDF": "Signed distance field to FogVolume surface (negative=inside, positive=outside)",
    "DENSITY": "Fog density (must be set to produce output)",
    "PARTICLE_INDEX": "Particle index",
    "PARTICLE_LIFETIME": "Particle lifetime (normalized)",
    "PARTICLE_START_LIFETIME": "Particle start lifetime",
    "PARTICLE_POSITION": "Particle position (model space)",
    "PARTICLE_VELOCITY": "Particle velocity (model space/s)",
    "PARTICLE_COLOR": "Particle color",
    "PARTICLE_CUSTOM": "Particle custom data",
    "PARTICLE_FLAG_ALIVE": "Particle alive flag",
    "PARTICLE_FLAG_DEAD": "Particle dead flag",
    "PARTICLE_FLAG_CUSTOM": "Particle custom flag",
    "PARTICLE_GLOBAL_AABB": "Particle global AABB",
    "EMISSION_TRANSFORM": "Emission transform matrix (model space → world space)",
    "VELOCITY": "Particle velocity (read-write)",
    "MASS": "Particle mass (read-write)",
    "ACTIVE": "Whether the particle is active (read-write)",
    "RESTART": "Whether the particle restarts (read-write)",
    "CUSTOM": "Custom particle data (read-write)",
    "TRANSFORM": "Particle transform matrix (read-write)",
    "LIFETIME": "Particle lifetime",
    "LIGHT_COLOR": "Light color (read-only)",
    "LIGHT_DIRECTION": "Light direction (read-only)",
    "SPECULAR_AMOUNT": "Specular amount (2.0 for omni/spot, 1.0 for directional)",
    "LIGHT_IS_DIRECTIONAL": "Whether the current light is directional",
    "DIFFUSE_LIGHT": "Diffuse light result (accumulate with +=)",
    "SPECULAR_LIGHT": "Specular light result (accumulate with +=)",
    "ATTENUATION": "Light attenuation (read-write)",
    "LIGHT": "Light color (read-write)",
    "LIGHT_ENERGY": "Light energy (read-write)",
    "LIGHT_DIFFUSE": "Diffuse lighting (read-write)",
    "LIGHT_SPECULAR": "Specular lighting (read-write)",
    "texture": "Sample a 2D texture",
    "textureLod": "Sample a texture with explicit LOD",
    "textureProj": "Projective texture sampling",
    "textureGrad": "Sample a texture using explicit gradients",
    "textureCube": "Sample a cubemap texture",
    "textureCubeLod": "Sample a cubemap texture with explicit LOD",
    "textureArray": "Sample a 2D texture array",
    "mix": "Linear interpolation. Two modes: mix(a, b, float t) scalar blend, mix(a, b, vecX t) component-wise blend",
    "clamp": "Clamp value to [min, max] range. Supports vecX and float parameters",
    "step": "Step function (returns 0 if x < edge, 1 otherwise). Supports float and vecX parameters",
    "smoothstep": "Smooth step function (Hermite interpolation). Supports float and vecX parameters",
    "sin": "Sine function (x in radians)",
    "cos": "Cosine function (x in radians)",
    "tan": "Tangent function (x in radians)",
    "asin": "Arcsine (returns [-π/2, π/2])",
    "acos": "Arccosine (returns [0, π])",
    "atan": "Arctangent (returns [-π, π])",
    "atan2": "Arctangent with quadrant determination",
    "sinh": "Hyperbolic sine",
    "cosh": "Hyperbolic cosine",
    "tanh": "Hyperbolic tangent",
    "asinh": "Inverse hyperbolic sine",
    "acosh": "Inverse hyperbolic cosine",
    "atanh": "Inverse hyperbolic tangent",
    "pow": "x raised to the power y",
    "sqrt": "Square root",
    "inversesqrt": "Inverse square root (1/√x)",
    "exp": "e raised to the power x",
    "exp2": "2 raised to the power x",
    "log": "Natural logarithm (base e)",
    "log2": "Base-2 logarithm",
    "length": "Vector length (√(x₀² + x₁² + ...))",
    "distance": "Distance between two points (length(a - b))",
    "dot": "Dot product (a₀b₀ + a₁b₁ + ...)",
    "cross": "Cross product (returns a vector perpendicular to a and b)",
    "normalize": "Normalize vector (x / length(x))",
    "reflect": "Reflection vector (I - 2.0 * dot(N, I) * N)",
    "refract": "Refraction vector (based on refractive index eta)",
    "faceforward": "Face-forward normal (dot(Nref, I) < 0 ? N : -N)",
    "abs": "Absolute value",
    "sign": "Sign function (1 if x > 0, -1 if x < 0, 0 otherwise)",
    "floor": "Floor (largest integer ≤ x)",
    "ceil": "Ceil (smallest integer ≥ x)",
    "round": "Round to nearest integer",
    "trunc": "Truncate fractional part (round toward zero)",
    "fract": "Fractional part (x - floor(x))",
    "mod": "Modulo (x - y * floor(x/y))",
    "min": "Minimum value",
    "max": "Maximum value",
    "determinant": "Matrix determinant",
    "transpose": "Matrix transpose",
    "inverse": "Matrix inverse",
    "outerProduct": "Outer product (returns matX matrix)",
    "vec2": "2-component floating-point vector. Suitable for UV coordinates, 2D positions.",
    "vec3": "3-component floating-point vector. Suitable for colors (RGB), 3D positions, normals.",
    "vec4": "4-component floating-point vector. Suitable for colors (RGBA), homogeneous coordinates.",
    "mat2": "2x2 floating-point matrix (4 elements).",
    "mat3": "3x3 floating-point matrix (9 elements). Suitable for 3x3 transformation matrices.",
    "mat4": "4x4 floating-point matrix (16 elements). Suitable for model/view/projection matrices.",
    "bool": "Boolean value. true or false.",
    "int": "Signed 32-bit integer. Suitable for counting, indexing, etc.",
    "uint": "Unsigned 32-bit integer.",
    "float": "Single-precision floating point number. Suitable for scalar values (time, scale, intensity, etc.).",
    "radians": "Convert degrees to radians",
    "degrees": "Convert radians to degrees",
    "noise": "Noise function (1D-4D). Type depends on project noise settings, returns [-1, 1]",
    "noise_perlin": "Perlin noise (1D-4D), returns [-1, 1]",
    "noise_simplex": "Simplex noise (1D-4D), returns [-1, 1]",
    "dfdx": "Screen-space partial derivative in x. Only available in fragment() and light()",
    "dfdy": "Screen-space partial derivative in y. Only available in fragment() and light()",
    "fwidth": "Sum of absolute partial derivatives: abs(dFdx(p)) + abs(dFdy(p))",
    "hash": "Hash function (returns 0..1)",
    "rand": "Random number (0..1, based on input)",
    "attenuation": "Light attenuation calculation",
    "blend_mix": "Mix blend mode (alpha is transparency), default mode",
    "blend_add": "Additive blend mode",
    "blend_sub": "Subtractive blend mode",
    "blend_mul": "Multiplicative blend mode",
    "blend_premul_alpha": "Pre-multiplied alpha blend mode (fully transparent=additive, fully opaque=mix)",
    "depth_draw_never": "Never draw depth",
    "depth_draw_always": "Always draw depth (opaque and transparent)",
    "depth_draw_opaque": "Only draw depth for opaque geometry",
    "depth_draw_alpha_prepass": "Perform opaque depth pre-pass for transparent geometry",
    "depth_prepass_alpha": "Perform opaque depth pre-pass for transparent geometry",
    "depth_test_disabled": "Disable depth testing",
    "depth_test_default": "Depth test: discard pixel if behind another pixel",
    "depth_test_inverted": "Inverted depth test: discard pixel if in front of another pixel; useful for stencil effects",
    "cull_disabled": "Disable culling (double-sided rendering)",
    "cull_front": "Cull front faces",
    "cull_back": "Cull back faces (default)",
    "unshaded": "Only show albedo, no lighting/shading calculations; faster rendering",
    "vertex_lighting": "Use vertex lighting instead of per-pixel lighting",
    "light_disabled": "Disable lighting",
    "light_enabled": "Enable lighting",
    "shadows_disabled": "Disable shadow calculations in the shader (doesn't receive shadows, but can still cast)",
    "shadows_enabled": "Enable shadows",
    "shadow_to_opacity": "Light modifies alpha, making shadowed areas opaque and non-shadowed areas transparent (for AR shadow overlay on camera)",
    "ambient_light_disabled": "Disable ambient light and radiance map contribution",
    "ambient_light_enabled": "Enable ambient light",
    "fog_disabled": "Disable receiving depth-based fog or volumetric fog (useful for blending materials like particles)",
    "diffuse_burley": "Burley (Disney PBS) diffuse model (default)",
    "diffuse_lambert": "Lambert diffuse model",
    "diffuse_lambert_wrap": "Lambert-wrap diffuse model (roughness-aware)",
    "diffuse_toon": "Toon diffuse model",
    "specular_schlick_ggx": "Schlick-GGX direct light specular lobe (default)",
    "specular_toon": "Toon direct light specular lobe",
    "specular_disabled": "Disable direct light specular lobe (does not affect reflections)",
    "skip_vertex_transform": "VERTEX, NORMAL, TANGENT, and BINORMAL must be transformed manually in vertex()",
    "world_vertex_coords": "VERTEX, NORMAL, TANGENT, and BINORMAL are modified in world space instead of model space",
    "ensure_correct_normals": "Use when applied to non-uniformly scaled meshes (currently not implemented)",
    "particle_trails": "Enable trails when used on particle geometry",
    "particle_collisions_disabled": "Disable particle collisions",
    "particle_collisions_enabled": "Enable particle collisions",
    "alpha_to_coverage": "Alpha-to-coverage anti-aliasing mode",
    "alpha_to_coverage_and_one": "Alpha-to-coverage anti-aliasing mode (variant)",
    "sss_mode_skin": "Subsurface scattering skin mode (optimized for human skin, enhances red channel)",
    "use_half_res_pass": "Render sky using half-resolution pass (performance optimization)",
    "use_quarter_res_pass": "Render sky using quarter-resolution pass (performance optimization)",
    "disable_fog": "Disable fog influence on the sky",
    "wireframe": "Draw geometry with lines (for troubleshooting)",
    "debug_shadow_splits": "Draw each directional light shadow split in a different color (for troubleshooting)",
    "do_not_delay_visibility": "Do not delay visibility (Canvas Item only)",
    "canvas_item": "Shader for 2D rendering. Can access 2D-specific variables such as UV, COLOR, TEXTURE. Used with 2D nodes like Sprite, Polygon2D, Line2D.",
    "spatial": "Shader for 3D rendering. Supports vertex transforms, lighting calculations, shadows, and other 3D features. Used with 3D nodes like MeshInstance3D, CSG.",
    "particles": "Shader for particle systems. Can control particle position, color, size, and other properties. Used with Particles or CPUParticles nodes.",
    "sky": "Shader for rendering the sky. Can access sky-specific variables such as EYEDIR, SCREEN_UV, SKY_COORDS. Used for dynamic skies, panoramic skies.",
    "fog": "Shader for volumetric fog effects. Can control fog color, density, emission, and other properties. Used with FogVolume nodes.",
    "void": "No return value. Used to declare functions that don't return a value.",
    "ivec2": "2-component integer vector.",
    "ivec3": "3-component integer vector.",
    "ivec4": "4-component integer vector.",
    "uvec2": "2-component unsigned integer vector.",
    "uvec3": "3-component unsigned integer vector.",
    "uvec4": "4-component unsigned integer vector.",
    "bvec2": "2-component boolean vector.",
    "bvec3": "3-component boolean vector.",
    "bvec4": "4-component boolean vector.",
    "sampler2D": "2D texture sampler. Used to read uniform-bound 2D textures. Can only be used in uniform declarations.",
    "samplerCube": "Cubemap sampler. Used to read environment maps, skybox textures. Can only be used in uniform declarations.",
    "sampler2DArray": "2D texture array sampler. Can access multiple texture layers simultaneously. Can only be used in uniform declarations.",
    "hint_white_texture": "Texture defaults to white",
    "hint_black_albedo": "Texture defaults to black (albedo map)",
    "hint_normal": "Specify texture as a normal map",
    "hint_depth_texture": "Specify texture as a depth map",
    "hint_screen_texture": "Specify texture as a screen texture",
    "hint_black": "Texture defaults to black",
    "source_color": "Specify color as source color (no color space conversion); applies to vec4",
    "hint_color": "Specify that this uniform is a color value; the inspector shows a color picker. Only applies to vec4",
    "hint_range": "Add a range slider adjustable in the inspector. Format: hint_range(min, max, step)",
    "hint_enum": "Enum options selectable in the inspector. Format: hint_enum(\"opt1\", \"opt2\")",
    "hint_exp_range": "Exponential range slider, suitable for logarithmic value adjustments. Format: hint_exp_range(min, max, step)",
    "hint_multiline_text": "Multi-line text input, suitable for longer string input",
    "hint_linked_port": "Linked port; can connect other node outputs to this uniform in the editor",
    "hint_file": "File picker; browse files in the inspector",
    "hint_dir": "Directory picker; browse directories in the inspector",
    "filter_nearest": "Use nearest-neighbor filtering (pixelated effect); suitable for pixel art",
    "filter_linear": "Use linear filtering (smooth interpolation); suitable for smooth textures",
    "filter_nearest_mipmap": "Nearest-neighbor filtering + mipmapping (pixelated at distance)",
    "filter_linear_mipmap": "Linear filtering + mipmapping (smooth at distance)",
    "repeat_enable": "Enable texture repeating (tiling effect)",
    "repeat_disable": "Disable texture repeating (edge clamp/stretch)",
    "flags_unused_uvs": "Mark that this uniform does not use UV coordinates",
    "flags_uses_screen_uv": "Mark that this uniform uses screen UV coordinates",
    "flags_uses_depth": "Mark that this uniform uses depth information",
    "flags_uses_time": "Mark that this uniform uses the TIME variable",
    "flags_uses_alpha": "Mark that this uniform uses the alpha channel",
    "flags_albedo_tex_force_srgb": "Force albedo texture to use sRGB color space",
    "flags_do_vertex_lighting": "Force use of vertex lighting",

    // 关键字（仅不与其他描述冲突的条目）
    "shader_type": "Declare shader type. Must be the first line of the file. Format: shader_type type;",
    "render_mode": "Set rendering mode options. Controls blending, culling, lighting, etc.",
    "uniform": "Declare an externally adjustable parameter. Editable in the inspector.",
    "varying": "Pass data between vertex() and fragment() functions.",
    "const": "Constant declaration. Value is determined at compile time and cannot be modified.",
    "struct": "Declare a struct type. Used to group multiple related variables.",
    "in": "Input parameter or input variable declaration. Identifies a variable passed from the previous stage.",
    "out": "Output parameter or output variable declaration. Identifies a variable passed to the next stage.",
    "inout": "Input-output parameter. Can be read from the caller and written back. Used in function parameters.",
    "if": "Conditional branch statement. Executes different code blocks based on conditions.",
    "else": "Code block executed when the if condition is false.",
    "for": "For loop. Iterates a known number of times. Format: for (init; condition; increment)",
    "while": "While loop. Repeats a code block while the condition is true.",
    "do": "Do-while loop. Executes the code block once before checking the condition.",
    "return": "Return a value from a function.",
    "break": "Break out of the current loop or switch block.",
    "continue": "Skip the remaining part of the current loop iteration and proceed to the next.",
    "switch": "Multi-branch selection statement. Matches the expression value to corresponding case branches.",
    "case": "A branch in a switch statement. Followed by a constant value and a colon.",
    "default": "Default branch in a switch statement. Executed when no case matches.",
    "discard": "Discard the current fragment without further processing. Only usable in fragment().",
    "vertex": "Vertex shader function. Modifies vertex position, normal, UV and other attributes.",
    "fragment": "Fragment shader function. Computes the final color for each pixel.",
    "light": "Light shader function. Custom lighting calculations (spatial only).",

    // 附加标注
    "sampler_uniform_only": "Samplers are only valid in uniform declarations",
    "user_var_description": "User-declared variable",

    // stencil_mode values
    "stencil_mode": "Set stencil buffer operation (experimental, spatial only). Format: stencil_mode operation, compare, ref_value;",
    "experimental_stencil": "is an experimental feature. The API may change in future versions.",
    "write": "Write the reference value to the stencil buffer",
    "write_if_depth_fail": "Write reference value to the stencil buffer when depth test fails",
    "compare_always": "Always pass the stencil test",
    "compare_equal": "Pass stencil test if the reference value equals the stencil buffer value",
    "compare_greater": "Pass stencil test if the reference value is greater than the stencil buffer value",
    "compare_greater_or_equal": "Pass stencil test if the reference value is greater than or equal to the stencil buffer value",
    "compare_less": "Pass stencil test if the reference value is less than the stencil buffer value",
    "compare_less_or_equal": "Pass stencil test if the reference value is less than or equal to the stencil buffer value",
    "compare_not_equal": "Pass stencil test if the reference value does not equal the stencil buffer value",

    // CanvasItem built-in variables
    "CANVAS_MATRIX": "World space to canvas space transform",
    "SCREEN_MATRIX": "Canvas space to clip space transform",
    "REGION_RECT": "Visible area of the sprite region (x, y, width, height)",
    "AT_LIGHT_PASS": "Always false in vertex; true in fragment when in light pass",
    "SPECULAR_SHININESS_TEXTURE": "Specular shininess texture of this object",
    "SPECULAR_SHININESS": "Specular shininess color from texture",
    "NORMAL_TEXTURE": "Default 2D normal texture",
    "SHADOW_VERTEX": "Same as VERTEX but can be written to alter shadows",
    // CanvasItem light function
    "LIGHT_POSITION": "Position of the Light2D in screen space (0,0,0 for DirectionalLight2D)",
    "SHADOW_MODULATE": "Multiply shadows cast at this point by this color",
};
